<?php
/**
 * Genesis Framework.
 *
 * WARNING: This file is part of the core Genesis Framework. DO NOT edit this file under any circumstances.
 * Please do all modifications in the form of a child theme.
 *
 * @package Genesis\Templates
 * @author  StudioPress
 * @license GPL-2.0+
 * @link    http://my.studiopress.com/themes/genesis/
 */

genesis_structural_wrap( 'site-inner', 'close' );
genesis_markup( array(
	'close'   => '</div>',
	'context' => 'site-inner',
) );

do_action( 'genesis_before_footer' );
do_action( 'genesis_footer' );
do_action( 'genesis_after_footer' );

genesis_markup( array(
	'close'   => '</div>',
	'context' => 'site-container',
) );

do_action( 'genesis_after' );
wp_footer(); // We need this for plugins.

if(!isset($_COOKIE['eucookie'])) { ?>
		<script type="text/javascript">
		function SetCookie(c_name,value,expiredays)
		{
		var exdate=new Date()
		exdate.setDate(exdate.getDate()+expiredays)
		document.cookie=c_name+ "=" +escape(value)+";path=/"+((expiredays==null) ? "" : ";expires="+exdate.toGMTString())
		}
		</script>
		<div id="cookielaw">
			<span class="interior">
				Utilizamos cookies propias y de terceros para mejorar nuestros servicios. Si continua navegando, consideramos que acepta su uso. Puede obtener más información
				<a href="<?php echo esc_url( home_url( '/' ) ); ?>aviso-legal/" target="_blank" class="cli-plugin-main-link">Aquí</a> 
				<span class="elboton" onclick="lascookies();">Acepto</span>
			</span>
		</div>
		<script type="text/javascript">
		if( document.cookie.indexOf("eucookie") ===-1 ){
			document.getElementById('cookielaw').style.display = 'block'; 
		}
		function lascookies() {
			SetCookie('eucookie','eucookie',365*10)
			var element = document.getElementById("cookielaw");
			element.parentNode.removeChild(element);
		};
		
		</script>
	<?php } ?>
<script>
function responsivemenu() {
    var x = document.getElementById("myTopnav");
    var y = document.getElementById("myTopbutton");
    if (x.className === "topnav") {
        x.className += " responsive";
        y.className += " menu_is_opened";
    } else {
        x.className = "topnav";
        y.className = "wprmenu_icon";
    }
}
</script>
<div class="carritocontainer">
	<div class="carritoover" onclick="$('.carritocontainer').hide();"></div>
<div class="carrito">

</div>
</div>
	<?php

genesis_markup( array(
	'close'   => '</body>',
	'context' => 'body',
) );

?>
</html>

<link rel='stylesheet' id='genesis-sample-css'  href='<?php echo get_site_url();?>/wp-content/themes/genesis-sample/js/fa/css/all.min.css' type='text/css' media='all' />
<link rel='stylesheet' id='genesis-sample-css'  href='<?php echo get_site_url();?>/wp-content/themes/genesis-sample/style3.css' type='text/css' media='all' />
<link rel='stylesheet' id='genesis-sample-fonts-css'  href='//fonts.googleapis.com/css?family=Source+Sans+Pro%3A400%2C600%2C700&#038;ver=2.3.0' type='text/css' media='all' />
  <script type="text/javascript" src="<?php echo get_site_url();?>/wp-content/themes/genesis-sample/js/prestashop.js" ></script>
<?php if (is_user_logged_in() ) { ?>
<link rel='stylesheet' id='admin-bar-css'  href='<?php echo get_site_url();?>/wp-includes/css/dashicons.min.css?ver=4.8.2' type='text/css' media='all' />
<link rel='stylesheet' id='admin-bar-css'  href='<?php echo get_site_url();?>/wp-includes/css/admin-bar.min.css?ver=4.8.2' type='text/css' media='all' />
<link rel='stylesheet' id='yoast-seo-adminbar-css'  href='<?php echo get_site_url();?>/wp-content/plugins/wordpress-seo/css/dist/adminbar-571.min.css?ver=5.7.1' type='text/css' media='all' />
<?php };?>
<div id="fb-root"></div>
<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = 'https://connect.facebook.net/es_LA/sdk.js#xfbml=1&version=v3.1&appId=175100815901426&autoLogAppEvents=1';
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>

<script>
$(document).ready(function() {
	$('.hidseo').hide();
});
</script>