<?php
/**
 * Genesis Framework.
 *
 * WARNING: This file is part of the core Genesis Framework. DO NOT edit this file under any circumstances.
 * Please do all modifications in the form of a child theme.
 *
 * @package Genesis\Templates
 * @author  StudioPress
 * @license GPL-2.0+
 * @link    http://my.studiopress.com/themes/genesis/
 */

do_action( 'genesis_doctype' );
do_action( 'genesis_title' );
do_action( 'genesis_meta' );
wp_head(); // We need this for plugins.
?>
    <meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
	<link href="http://localhost/sillamania.es/maquetas/_/css/bootstrap.min.css" rel="stylesheet">
	<link href="http://localhost/sillamania.es/maquetas/_/css/styles.css" rel="stylesheet">
	<!--[if lt IE 9]>
	<script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
	<script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
	<![endif]-->
	<!--[if lt IE 10]>
	    <link rel="stylesheet" type="text/css" href="_/css/ie.css" />
	<![endif]-->
	
</head>
<?php
genesis_markup( array(
	'open'   => '<body %s>',
	'context' => 'body',
) );
do_action( 'genesis_before' );

genesis_markup( array(
	'open'   => '<div %s>',
	'context' => 'site-container',
) );

?>

<?php
/*
 * Abrimos sesion para guardar
 * una variable del modal
 */
error_reporting(E_ERROR);
session_start();

echo '
	<script>
		function load_modal_window(){
			setTimeout(function(){ 
				jQuery(".modal-bienvenida").modal("show");
			}, 3000);
		}
	</script>';

if (!$_SESSION['modal']){
	$_SESSION['modal']  = 'inicial'; 
	echo '<script>jQuery(document).ready(function() {load_modal_window()})</script>';
}
?>

<?php
	genesis_markup( array(
		'open'   => '<div %s>',
		'context' => 'site-inner',
	) );
	genesis_structural_wrap( 'site-inner' );
?>

