<?php
/**
 * Genesis Framework.
 *
 * WARNING: This file is part of the core Genesis Framework. DO NOT edit this file under any circumstances.
 * Please do all modifications in the form of a child theme.
 *
 * @package Genesis\Templates
 * @author  StudioPress
 * @license GPL-2.0+
 * @link    http://my.studiopress.com/themes/genesis/
 */

// Remove default loop
remove_action( 'genesis_sidebar', 'genesis_do_sidebar' );
remove_action( 'genesis_loop', 'genesis_do_loop' );
add_action( 'genesis_loop', 'wps_category_do_loop_intro', 5 );
/**
 * Custom Loop Intro
 *
 */

function wps_category_do_loop_intro() {
echo '<article id="post" class="post type-post status-publish format-standard has-post-thumbnail es-ES entry">';
		$s = isset( $_GET["s"] ) ? $_GET["s"] : "";
		// accepts any wp_query args.
		$args = (array(
			's' => $s,
			'posts_per_page' => 5,
			'order' => 'ASC',
			'orderby' => 'title'
		));
		$query = new WP_Query( $args );
		if ( $query->have_posts() ) {
			echo '<div class="row" style="max-width:1200px;margin:0 auto;">';
				foreach ($query->get_posts() as $post) {
					if(get_permalink($post->ID)!=home_url()) {
					$img = wp_get_attachment_image_src( get_post_thumbnail_id($post->ID), 'medium'); 
					echo '<div class="col-md-4 col-sm-6 col-xs-12">
							<div style="padding: 10px;">
								<div class="row categoprod">
									<div class="col-xs-12 col-sm-3 col-md-12">';
									if($img[0]!="") {
										echo '<a style="width:100%;" href="'.get_permalink($post->ID).'"><img style="width:100%;" src="'.$img[0].'" alt="'.$post->post_title.'" title="'.$post->post_title.'"></a>';
									} else {
										echo '<a style="width:100%;" href="'.get_permalink($post->ID).'"><img style="width:100%;" src="'.get_site_url().'/wp-content/uploads/dicorocuadrado.jpg" alt="'.$post->post_title.'" title="'.$post->post_title.'"></a>';
									}
									echo '</div>
									<div class="col-xs-12 col-sm-8 col-md-12">
										<h3><a style="color:black;" href="'.get_permalink($post->ID).'">'.$post->post_title.'</a></h3></div>
								</div>
							</div>
						</div>';
					};
				};
				$temps=str_replace(' ','%',$s);
				$que="select * from `ps_product_lang` where (name like '%".$temps."%' OR  description like '%".$temps."%' OR  description_short like '%".$temps."%') AND id_lang=1 LIMIT 30";
				$query2 = $GLOBALS['wpdb']->get_results( $que, OBJECT );
				foreach ($query2 as $row) {
					$prod=get_product($row->id_product);
						$link="http://promosillas.com/tiendaonline/".$prod['id_product']."-".$valor['product_attribute']."-".$prod['link_rewrite'].".html";
					echo '<div class="col-md-4 col-sm-6 col-xs-12">
							<div style="padding: 10px;">
								<div class="row categoprod">
									<div class="col-xs-12">';
									if($prod['imagen']['medium_default']!="") {
										echo '<a style="width:100%;" href="'.$link.'"><img style="width:100%;" src="'.$prod['imagen']['medium_default'].'" alt="'.$row->name.'" title="'.$row->name.'"></a>';
										} else {
										echo '<a style="width:100%;" href="'.$link.'"><img style="width:100%;" src="'.get_site_url().'/wp-content/uploads/dicorocuadrado.jpg" alt="'.$row->name.'" title="'.$row->name.'"></a>';
										}
									echo '</div>
									<div class="col-xs-12">';
										$precio=round($prod['pricetax'],0)."€";
										$precioneto=round($prod['netprice'],0)."€";
											if($prod['netprice']<$prod['pricetax'] && $prod['netprice']>0) {
											echo '<div class="tituloprod">
												<a href="'.$link.'">'.$prod['name'].' '.$valor['name'].'</a>
												<span class="elprecio">
												<span class="preciodto">'.$precioneto.'</span>
												<span class="precioantes">'.$precio.'</span>
												</span>
											</div>';
											} else {
											echo '<div class="tituloprod">
												<a href="'.$link.'">'.$prod['name'].' '.$valor['name'].'</a>
												<span class="elprecio">
												<span class="preciodto">'.$precio.'</span>
												</span>
											</div>';
											};
									echo '</div>
								</div>';	
							echo '</div>
						</div>';
				}
			echo '</div>';
		};
echo "</article>";
}

genesis();
